### ISSUE TITLE
关于导入路径问题

### ISSUE THREAD

**Issue by aiadaniel** [Golangltd/LollipopGo#3]
1.golang的版本是多少，我本地1.11.4
2.我下载的路径：F:\gospace\src\github.com\mafei198\gos
但导入到idea时，依旧显示找不到包，费解（截图[https://imgchr.com/i/ZJc6nH](url)） 不知道您能不能看到截图，显示路径还是需要加上src，才能对应得上

**Comment by cserli** [comment]
版本不是问题，你加我微信：cserli
 
------------------



李海彬
成都贝游特教育科技有限公司


 联系我









 




------------------ 原始邮件 ------------------
发件人: "aiadaniel"<notifications@github.com>; 
发送时间: 2019年7月2日(星期二) 晚上6:01
收件人: "Golangltd/LollipopGo"<LollipopGo@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [Golangltd/LollipopGo] 关于导入路径问题 (#3)




1.golang的版本是多少，我本地1.11.4
 2.我下载的路径：F:\gospace\src\github.com\mafei198\gos
 但导入到idea时，依旧显示找不到包，费解（截图https://imgchr.com/i/ZJc6nH）
 
&mdash;
