### ISSUE TITLE
www.gameais.com 打不开 504

### ISSUE THREAD

**Issue by bournes** [Golangltd/LollipopGo#5]
www.gameais.com 打不开 504

**Comment by cserli** [comment]
嗯&nbsp; 这个网站已经无法访问了&nbsp; 请关注微信公众账号：Golang语言游戏服务器&nbsp; ；文档及视频都有说明
&nbsp;




李海彬
成都贝游特教育科技有限公司


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月11日(星期四) 晚上6:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Golangltd/LollipopGo] www.gameais.com 打不开 504 (#5)





 
www.gameais.com 打不开 504
